// Code generated by protoc-gen-go. DO NOT EDIT.
// source: push.ext.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PushMsg_Type int32

const (
	PushMsg_PUSH      PushMsg_Type = 0
	PushMsg_ROOM      PushMsg_Type = 1
	PushMsg_BROADCAST PushMsg_Type = 2
)

var PushMsg_Type_name = map[int32]string{
	0: "PUSH",
	1: "ROOM",
	2: "BROADCAST",
}

var PushMsg_Type_value = map[string]int32{
	"PUSH":      0,
	"ROOM":      1,
	"BROADCAST": 2,
}

func (x PushMsg_Type) String() string {
	return proto.EnumName(PushMsg_Type_name, int32(x))
}

func (PushMsg_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9b36e2192823d216, []int{0, 0}
}

//消息格式
type PushMsg struct {
	Type                 PushMsg_Type `protobuf:"varint,1,opt,name=type,proto3,enum=pb.PushMsg_Type" json:"type,omitempty"`
	Operation            int32        `protobuf:"varint,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Speed                int32        `protobuf:"varint,3,opt,name=speed,proto3" json:"speed,omitempty"`
	Server               string       `protobuf:"bytes,4,opt,name=server,proto3" json:"server,omitempty"`
	RoomId               string       `protobuf:"bytes,5,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Keys                 []int64      `protobuf:"varint,6,rep,packed,name=keys,proto3" json:"keys,omitempty"`
	Msg                  []byte       `protobuf:"bytes,7,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PushMsg) Reset()         { *m = PushMsg{} }
func (m *PushMsg) String() string { return proto.CompactTextString(m) }
func (*PushMsg) ProtoMessage()    {}
func (*PushMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b36e2192823d216, []int{0}
}

func (m *PushMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMsg.Unmarshal(m, b)
}
func (m *PushMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMsg.Marshal(b, m, deterministic)
}
func (m *PushMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMsg.Merge(m, src)
}
func (m *PushMsg) XXX_Size() int {
	return xxx_messageInfo_PushMsg.Size(m)
}
func (m *PushMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PushMsg proto.InternalMessageInfo

func (m *PushMsg) GetType() PushMsg_Type {
	if m != nil {
		return m.Type
	}
	return PushMsg_PUSH
}

func (m *PushMsg) GetOperation() int32 {
	if m != nil {
		return m.Operation
	}
	return 0
}

func (m *PushMsg) GetSpeed() int32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *PushMsg) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *PushMsg) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *PushMsg) GetKeys() []int64 {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *PushMsg) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

type PushMsgReq struct {
	Message              *PushMsg `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMsgReq) Reset()         { *m = PushMsgReq{} }
func (m *PushMsgReq) String() string { return proto.CompactTextString(m) }
func (*PushMsgReq) ProtoMessage()    {}
func (*PushMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b36e2192823d216, []int{1}
}

func (m *PushMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMsgReq.Unmarshal(m, b)
}
func (m *PushMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMsgReq.Marshal(b, m, deterministic)
}
func (m *PushMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMsgReq.Merge(m, src)
}
func (m *PushMsgReq) XXX_Size() int {
	return xxx_messageInfo_PushMsgReq.Size(m)
}
func (m *PushMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_PushMsgReq proto.InternalMessageInfo

func (m *PushMsgReq) GetMessage() *PushMsg {
	if m != nil {
		return m.Message
	}
	return nil
}

type PushMsgReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMsgReply) Reset()         { *m = PushMsgReply{} }
func (m *PushMsgReply) String() string { return proto.CompactTextString(m) }
func (*PushMsgReply) ProtoMessage()    {}
func (*PushMsgReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b36e2192823d216, []int{2}
}

func (m *PushMsgReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMsgReply.Unmarshal(m, b)
}
func (m *PushMsgReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMsgReply.Marshal(b, m, deterministic)
}
func (m *PushMsgReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMsgReply.Merge(m, src)
}
func (m *PushMsgReply) XXX_Size() int {
	return xxx_messageInfo_PushMsgReply.Size(m)
}
func (m *PushMsgReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMsgReply.DiscardUnknown(m)
}

var xxx_messageInfo_PushMsgReply proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("pb.PushMsg_Type", PushMsg_Type_name, PushMsg_Type_value)
	proto.RegisterType((*PushMsg)(nil), "pb.PushMsg")
	proto.RegisterType((*PushMsgReq)(nil), "pb.PushMsgReq")
	proto.RegisterType((*PushMsgReply)(nil), "pb.PushMsgReply")
}

func init() { proto.RegisterFile("push.ext.proto", fileDescriptor_9b36e2192823d216) }

var fileDescriptor_9b36e2192823d216 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x86, 0xdd, 0x7c, 0x9a, 0x69, 0x0d, 0x61, 0x10, 0xdd, 0x83, 0x87, 0x10, 0x14, 0xe2, 0x25,
	0x87, 0xf6, 0x17, 0x54, 0x3d, 0xe8, 0xa1, 0xa4, 0x6c, 0xeb, 0x59, 0x1a, 0x32, 0xa4, 0x45, 0xe3,
	0xae, 0xbb, 0xa9, 0x98, 0x1f, 0xec, 0xff, 0x90, 0x7c, 0xa8, 0xbd, 0xbd, 0xef, 0x3c, 0x0c, 0xcc,
	0x33, 0x10, 0xaa, 0x83, 0xd9, 0x65, 0xf4, 0xd5, 0x64, 0x4a, 0xcb, 0x46, 0xa2, 0xa5, 0x8a, 0xe4,
	0x9b, 0x81, 0xbf, 0x3a, 0x98, 0xdd, 0xd2, 0x54, 0x78, 0x0d, 0x4e, 0xd3, 0x2a, 0xe2, 0x2c, 0x66,
	0x69, 0x38, 0x8b, 0x32, 0x55, 0x64, 0x23, 0xca, 0x36, 0xad, 0x22, 0xd1, 0x53, 0xbc, 0x82, 0x40,
	0x2a, 0xd2, 0xdb, 0x66, 0x2f, 0xdf, 0xb9, 0x15, 0xb3, 0xd4, 0x15, 0xff, 0x03, 0x3c, 0x07, 0xd7,
	0x28, 0xa2, 0x92, 0xdb, 0x3d, 0x19, 0x0a, 0x5e, 0x80, 0x67, 0x48, 0x7f, 0x92, 0xe6, 0x4e, 0xcc,
	0xd2, 0x40, 0x8c, 0x0d, 0x2f, 0xc1, 0xd7, 0x52, 0xd6, 0x2f, 0xfb, 0x92, 0xbb, 0x03, 0xe8, 0xea,
	0x53, 0x89, 0x08, 0xce, 0x2b, 0xb5, 0x86, 0x7b, 0xb1, 0x9d, 0xda, 0xa2, 0xcf, 0x18, 0x81, 0x5d,
	0x9b, 0x8a, 0xfb, 0x31, 0x4b, 0xa7, 0xa2, 0x8b, 0xc9, 0x2d, 0x38, 0xdd, 0x61, 0x78, 0x0a, 0xce,
	0xea, 0x79, 0xfd, 0x18, 0x9d, 0x74, 0x49, 0xe4, 0xf9, 0x32, 0x62, 0x78, 0x06, 0xc1, 0x9d, 0xc8,
	0x17, 0x0f, 0xf7, 0x8b, 0xf5, 0x26, 0xb2, 0x92, 0x39, 0xc0, 0xe8, 0x22, 0xe8, 0x03, 0x6f, 0xc0,
	0xaf, 0xc9, 0x98, 0x6d, 0x35, 0xc8, 0x4e, 0x66, 0x93, 0x23, 0x59, 0xf1, 0xcb, 0x92, 0x10, 0xa6,
	0x7f, 0x4b, 0xea, 0xad, 0x2d, 0xbc, 0xfe, 0x6f, 0xf3, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x43,
	0x72, 0x32, 0x2a, 0x49, 0x01, 0x00, 0x00,
}
